server:
  servlet:
    context-path: /api
  port: 8082
spring:
  profiles:
    active:
      - local
    group:
      local:
        - local-db
        - local-common
        - local-service
      dev:
        - dev-db
        - dev-common
        - dev-service
      prod:
        - prod-db
        - prod-common
        - prod-service
    include:
      - db
      - common
      - service

logging:
  level:
    com:
      post: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace