spring:
  config:
    activate:
      on-profile: local-service

service:
  j-user-service: http://localhost:8081
  j-authentication-service: http://localhost:8079


---
spring:
  config:
    activate:
      on-profile: prod-service

service:
  j-user-service: http://j-post-service:8081
  j-authentication-service: http://j-authentication-service:8079

